# Generated by Django 6.0.4 on 2026-08-19 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image de la catégorie')),
                ('icone', models.CharField(blank=True, help_text='Icône FontAwesome (ex: fa-oil-can)', max_length=50, null=True, verbose_name='Icône')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_active', models.BooleanField(default=True, verbose_name='Catégorie active')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produits',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='MarqueProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la marque')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques_produits/', verbose_name='Logo de la marque')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('est_active', models.BooleanField(default=True, verbose_name='Marque active')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marque de produit',
                'verbose_name_plural': 'Marques de produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UniteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name="Nom de l'unité")),
                ('abreviation', models.CharField(max_length=10, verbose_name='Abréviation')),
            ],
            options={
                'verbose_name': 'Unité de produit',
                'verbose_name_plural': 'Unités de produits',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description détaillée')),
                ('description_courte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description courte (pour les cartes)')),
                ('prix', models.DecimalField(decimal_places=0, default=0.0, max_digits=12, verbose_name='Prix (FCFA)')),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix promo (FCFA)')),
                ('date_debut_promo', models.DateTimeField(blank=True, null=True, verbose_name='Début de la promotion')),
                ('date_fin_promo', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la promotion')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('stock_min', models.IntegerField(default=5, verbose_name='Stock minimum (alerte)')),
                ('image_principale', models.ImageField(upload_to='produits/', verbose_name='Image principale')),
                ('compatible_avec', models.CharField(blank=True, help_text='Ex: Toyota, Nissan, Mercedes', max_length=255, null=True, verbose_name='Véhicules compatibles')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules', max_length=52, null=True, verbose_name='Tags (SEO)')),
                ('est_vedette', models.BooleanField(default=False, verbose_name='Produit en vedette')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible à la vente')),
                ('est_nouveau', models.BooleanField(default=False, verbose_name='Nouveau produit')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour génération automatique', max_length=200, null=True, unique=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='products_app.categorieproducts', verbose_name='Catégorie')),
                ('favoris_de', models.ManyToManyField(blank=True, limit_choices_to={'role': 'client'}, related_name='produits_favoris', to=settings.AUTH_USER_MODEL)),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='products_app.marqueproduit', verbose_name='Marque')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='products_app.uniteproduit', verbose_name='Unité de vente')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['ordre', '-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ProductAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], verbose_name='Note')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_produits', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='products_app.products', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Avis produit',
                'verbose_name_plural': 'Avis produits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, help_text="Description courte de l'image pour l'accessibilité", max_length=150, null=True, verbose_name='Texte alternatif (SEO)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Plus le chiffre est petit, plus l'image est affichée en premier", verbose_name="Ordre d'affichage")),
                ('est_principale', models.BooleanField(default=False, help_text="Cochez si cette image doit être l'image principale du produit", verbose_name='Image principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products_app.products', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image du produit',
                'verbose_name_plural': 'Images des produits',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
