# Generated by Django 6.0.4 on 2026-09-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock_min',
            field=models.IntegerField(default=3, verbose_name='Stock minimum (alerte)'),
        ),
    ]
