# Generated by Django 6.0.4 on 2026-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='commande',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('chargement', 'Chargement'), ('validee', 'Validée'), ('annulee', 'Annulée'), ('payee', 'Payée'), ('livraison', 'En livraison'), ('terminee', 'Terminée')], default='Chargement', max_length=20),
        ),
    ]
