# Generated by Django 6.0.4 on 2026-08-19 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
            ],
        ),
        migrations.CreateModel(
            name='TypeVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: SUV, Berline, Coupé', max_length=50, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='type_vehicule_images/%Y/%m/%d/', verbose_name='image')),
                ('icone', models.CharField(blank=True, help_text='Icône FontAwesome (ex: fa-car, fa-truck)', max_length=50, null=True, verbose_name='Icône')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type de véhicule',
                'verbose_name_plural': 'Types de véhicules',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('stock_min', models.IntegerField(default=1, verbose_name='Stock minimum (alerte)')),
                ('prix', models.DecimalField(decimal_places=0, max_digits=12)),
                ('kilometrage', models.IntegerField()),
                ('carburant', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique')], default='essence', max_length=20)),
                ('image_principale', models.ImageField(upload_to='vehicules/')),
                ('disponible', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('actualite', models.BooleanField(default=False)),
                ('est_vedette', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='Laissez vide pour génération automatique', max_length=200, null=True, unique=True)),
                ('favoris_de', models.ManyToManyField(blank=True, limit_choices_to={'role': 'client'}, related_name='vehicules_favoris', to=settings.AUTH_USER_MODEL)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicul', to='vehicul_app.marque')),
                ('type_vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicul_app.typevehicule', verbose_name='Type de véhicule')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicules_images/%Y/%m/%d/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text="Description courte de l'image pour l'accessibilité", max_length=200, null=True, verbose_name='Texte alternatif (SEO)')),
                ('ordre', models.PositiveIntegerField(default=0, help_text="Plus le chiffre est petit, plus l'image est affichée en premier", verbose_name="Ordre d'affichage")),
                ('est_principale', models.BooleanField(default=False, help_text="Cochez si cette image doit être l'image principale du véhicule", verbose_name='Image principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicul_app.vehicul')),
            ],
            options={
                'verbose_name': 'Image du véhicule',
                'verbose_name_plural': 'Images des véhicules',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
    ]
