# Generated by Django 6.0.4 on 2026-09-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicul_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicul',
            name='capacite_reservoir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacité du réservoir (L)'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='conso_moyenne_en_agglomération',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Consommation moyenne en agglomération (L/100km)'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='conso_moyenne_hors_agglomération',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Consommation moyenne hors agglomération (L/100km)'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='couleur',
            field=models.CharField(default='#3b82f6', help_text='Couleur en hexadécimal', max_length=7, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='type_de_pneus',
            field=models.CharField(default="Pneus d'origine", max_length=100, verbose_name='Type de pneus'),
        ),
    ]
