# Generated by Django 6.0.4 on 2026-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicul_app', '0002_vehicul_capacite_reservoir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicul',
            name='couleur',
        ),
        migrations.AddField(
            model_name='vehicul',
            name='couleur_exterieure',
            field=models.CharField(default='#3b82f6', help_text='Couleur en hexadécimal', max_length=7, verbose_name='Couleur extérieure'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='couleur_interieure',
            field=models.CharField(default='#f9fafb', help_text='Couleur en hexadécimal', max_length=7, verbose_name='Couleur intérieure'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='etat',
            field=models.CharField(blank=True, choices=[('neuf', 'Neuf'), ('occasion', 'Occasion')], default='neuf', max_length=20, null=True, verbose_name='État du véhicule'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='moteur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='motricite',
            field=models.CharField(blank=True, choices=[('awd', 'Traction intégrale (AWD)'), ('fw', 'Traction avant (FW)')], default='fw', max_length=20, null=True, verbose_name='Motricité'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='nombre_places',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='nombre_portes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='sieges',
            field=models.CharField(blank=True, choices=[('standard', 'Sièges standards'), ('ventilé', 'Sièges ventilés'), ('chauffant', 'Sièges chauffants'), ('massant', 'Sièges massants')], default='ventilé', max_length=20, null=True, verbose_name='Type de sièges'),
        ),
        migrations.AddField(
            model_name='vehicul',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
