# Generated by Django 6.0.4 on 2026-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicul_app', '0003_remove_vehicul_couleur_vehicul_couleur_exterieure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicul',
            name='carburant',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('electrique', 'Electrique'), ('hybride', 'Hybride')], default='essence', max_length=20),
        ),
    ]
