# Generated by Django 6.0.4 on 2026-08-19 14:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'actualité")),
                ('sous_titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sous-titre')),
                ('description', models.TextField(verbose_name='Description complète')),
                ('description_courte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description courte (pour les cartes)')),
                ('type', models.CharField(choices=[('evenement', 'Événement'), ('nouveaute', 'Nouveauté / Lancement'), ('communique', 'Communiqué de presse'), ('offre', 'Offre spéciale'), ('reception', 'Réception / Gala'), ('promotion', 'Promotion'), ('autre', 'Autre')], default='nouveaute', max_length=30, verbose_name="Type d'actualité")),
                ('image_principale', models.ImageField(upload_to='actualites/%Y/%m/%d/', verbose_name='Image principale')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='actualites/%Y/%m/%d/', verbose_name='Image 2')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='actualites/%Y/%m/%d/', verbose_name='Image 3')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='actualites/%Y/%m/%d/', verbose_name='Image 4')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='actualites/%Y/%m/%d/', verbose_name='Image 5')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='actualites/%Y/%m/%d/', verbose_name='Image 6')),
                ('video_file', models.FileField(blank=True, help_text='Formats : MP4, WebM, MOV', null=True, upload_to='actualites/videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'avi'])], verbose_name='Fichier vidéo')),
                ('video_url', models.URLField(blank=True, help_text='https://www.youtube.com/watch?v=...', null=True, verbose_name='Lien YouTube/Vimeo')),
                ('lien_externe', models.URLField(blank=True, help_text='Rediriger vers une page externe', null=True, verbose_name='Lien externe')),
                ('lien_interne', models.URLField(blank=True, help_text='Rediriger vers une page interne', null=True, verbose_name='Lien interne')),
                ('date_evenement', models.DateTimeField(help_text="Date à laquelle l'événement a lieu", verbose_name="Date de l'événement")),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('date_fin', models.DateTimeField(blank=True, help_text='Pour les offres ou événements avec durée', null=True, verbose_name='Date de fin')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('est_vedette', models.BooleanField(default=False, verbose_name='Mettre en vedette')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_evenement', '-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='AvisReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('google', 'Google Maps'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter')], max_length=20, verbose_name='Réseau social')),
                ('nom_utilisateur', models.CharField(max_length=100, verbose_name="Nom d'utilisateur")),
                ('message', models.TextField(verbose_name='Message')),
                ('date_publication', models.DateTimeField(verbose_name='Date de publication')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avis_reseaux/%Y/%m/%d/', verbose_name='Image/screenshot')),
                ('lien', models.URLField(blank=True, null=True, verbose_name='Lien vers le post')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Afficher')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis réseau social',
                'verbose_name_plural': 'Avis réseaux sociaux',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='VideoTemoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la vidéo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('video_file', models.FileField(blank=True, help_text='MP4, WebM, MOV (max 100MB)', null=True, upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov', 'avi'])], verbose_name='Fichier vidéo')),
                ('video_url', models.URLField(blank=True, help_text='https://www.youtube.com/watch?v=...', null=True, verbose_name='Lien YouTube/Vimeo')),
                ('embed_code', models.TextField(blank=True, help_text='Code iframe YouTube ou autre', null=True, verbose_name="Code d'intégration")),
                ('duree', models.PositiveIntegerField(blank=True, help_text='Durée en secondes', null=True, verbose_name='Durée')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prenom')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True, verbose_name='telephone')),
                ('date_rendez_vous', models.DateTimeField(verbose_name='Date et heure')),
                ('duree', models.PositiveIntegerField(default=60, verbose_name='Durée (minutes)')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_rendez_vous'],
            },
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='temoignages/%Y/%m/%d/', verbose_name='Photo')),
                ('message', models.TextField(verbose_name='Témoignage')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1 ⭐'), (2, '2 ⭐'), (3, '3 ⭐'), (4, '4 ⭐'), (5, '5 ⭐')], default=5, verbose_name='Note')),
                ('source', models.CharField(choices=[('site', 'Site KOZ'), ('facebook', 'Facebook'), ('google', 'Google Maps'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], default='site', max_length=50, verbose_name='Source')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('est_vedette', models.BooleanField(default=False, verbose_name='Mettre en vedette')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temoignages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['-date_creation'],
            },
        ),
    ]
