# Generated by Django 6.0.4 on 2026-09-02 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='client',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
    ]
