# Generated by Django 6.0.4 on 2026-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_rendezvous_email_alter_rendezvous_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='type',
            field=models.CharField(choices=[('tutos', 'Tutos & Conseils Auto'), ('nouveaute', 'Nouveauté / Lancement'), ('decouverte', 'Découvrir des modèles'), ('communique', 'Communiqué de presse'), ('offre', 'Offre spéciale'), ('reception', 'Réception / Gala'), ('promotion', 'Promotion'), ('autre', 'Autre')], default='nouveaute', max_length=30, verbose_name="Type d'actualité"),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='motif',
            field=models.TextField(verbose_name='Motif'),
        ),
    ]
