# Generated by Django 6.0.4 on 2026-08-19 14:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_propose', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('prix_vehicule', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('apport_demande', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('montant_finance', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('duree_mois', models.IntegerField(default=0)),
                ('mensualite', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('taux_interet', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frais_dossier', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True)),
                ('frais_garantie', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True)),
                ('total_du', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True)),
                ('financement_type', models.CharField(blank=True, choices=[('maison', 'Maison'), ('externe', 'Externe')], max_length=50, null=True)),
                ('financement_par', models.CharField(blank=True, choices=[('fidelis', 'Fidelis'), ('alios', 'Alios')], max_length=50, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'En cours de rédaction'), ('verification_document', "Dossier de l'offre en vérification"), ('en_attente_document', 'En attente de documents'), ('offre_document_rejete', "Documents de l'offre réjeté"), ('offre_document_valide', "Documents de l'offre validés"), ('offre_financement_fidelis', 'offre financement chez Fidelis'), ('offre_financement_alios', 'offre financement chez Alios'), ('offre_financement_maison', 'offre financement KOZ Services'), ('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Offre expirée')], default='brouillon', max_length=30)),
                ('type_offre', models.CharField(choices=[('simple', 'Offre simple'), ('demande', 'Offre liée à une demande'), ('offre_financement', 'Offre de financement')], default='simple', max_length=20)),
                ('signature_client', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('date_expiration', models.DateTimeField(default=datetime.datetime(2026, 9, 18, 14, 44, 34, 949387, tzinfo=datetime.timezone.utc))),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
