# Generated by Django 6.0.4 on 2026-08-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0002_initial'),
        ('commercial_app', '0001_initial'),
        ('leads_app', '0001_initial'),
        ('vehicul_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='demande_financement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='leads_app.demande_financement'),
        ),
        migrations.AddField(
            model_name='offre',
            name='dossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='client_app.documents'),
        ),
        migrations.AddField(
            model_name='offre',
            name='vehicule_propose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='vehicul_app.vehicul'),
        ),
    ]
