# Generated by Django 6.0.4 on 2026-08-19 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 18, 15, 22, 34, 561803, tzinfo=datetime.timezone.utc)),
        ),
    ]
