# Generated by Django 6.0.4 on 2026-08-21 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0003_alter_offre_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 20, 10, 35, 46, 902168, tzinfo=datetime.timezone.utc)),
        ),
    ]
