# Generated by Django 6.0.4 on 2026-08-22 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0010_alter_offre_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 21, 12, 19, 45, 891960, tzinfo=datetime.timezone.utc)),
        ),
    ]
