# Generated by Django 6.0.4 on 2026-09-02 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0011_alter_offre_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 2, 15, 14, 26, 616799, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='offre',
            name='financement_par',
            field=models.CharField(blank=True, choices=[('fidelis', 'Fidelis'), ('Koz', 'KOZ SERVICES')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'En cours de rédaction'), ('verification_document', "Dossier de l'offre en vérification"), ('en_attente_document', 'En attente de documents'), ('offre_document_rejete', "Documents de l'offre réjeté"), ('offre_document_valide', "Documents de l'offre validés"), ('offre_financement_fidelis', 'offre financement chez Fidelis'), ('offre_financement_maison', 'offre financement KOZ Services'), ('envoyee', 'Envoyée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('expiree', 'Offre expirée')], default='brouillon', max_length=30),
        ),
    ]
