# Generated by Django 6.0.4 on 2026-09-03 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0012_alter_offre_date_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 3, 21, 43, 28, 586376, tzinfo=datetime.timezone.utc)),
        ),
    ]
