# Generated by Django 6.0.4 on 2026-09-08 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0015_alter_offre_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 8, 21, 43, 50, 719667, tzinfo=datetime.timezone.utc)),
        ),
    ]
