# Generated by Django 6.0.4 on 2026-09-09 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0016_alter_offre_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 9, 20, 56, 29, 738445, tzinfo=datetime.timezone.utc)),
        ),
    ]
