# Generated by Django 6.0.4 on 2026-09-19 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0017_alter_offre_date_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 19, 12, 25, 41, 594260, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='offre',
            name='duree_mois',
            field=models.IntegerField(default=1),
        ),
    ]
