# Generated by Django 6.0.4 on 2026-09-20 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial_app', '0018_alter_offre_date_expiration_alter_offre_duree_mois'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date_expiration',
            field=models.DateTimeField(default=datetime.datetime(2026, 10, 20, 22, 7, 47, 744778, tzinfo=datetime.timezone.utc)),
        ),
    ]
