# Generated by Django 6.0.4 on 2026-08-19 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.IntegerField()),
                ('immatriculation', models.CharField(blank=True, max_length=20, null=True)),
                ('kilometrage_actuel', models.IntegerField()),
                ('origine', models.CharField(choices=[('koz', 'Acheté chez KOZ'), ('externe', 'Véhicule extérieur')], default='externe', max_length=20)),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Révision complète'), ('pneumatiques', 'Pneumatiques'), ('freins', 'Freins/plaquettes'), ('climatisation', 'Climatisation'), ('batterie', 'Batterie'), ('courroie', 'Courroie de distribution'), ('autre', 'Autre')], max_length=30)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_prochaine', models.DateField()),
                ('date_derniere', models.DateField(blank=True, null=True)),
                ('kilometrage_prochain', models.IntegerField()),
                ('kilometrage_dernier', models.IntegerField(blank=True, null=True)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('montant_reel', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('effectuee', 'Effectuée'), ('depassee', 'Dépassée (non faite)'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('rappel_envoye', models.BooleanField(default=False)),
                ('date_rappel', models.DateField(blank=True, null=True)),
                ('sms_envoye', models.BooleanField(default=False)),
                ('email_envoye', models.BooleanField(default=False)),
                ('notes_client', models.TextField(blank=True)),
                ('notes_technicien', models.TextField(blank=True, verbose_name='Remarque technicien')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_prochaine'],
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni_passeport', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Photocopie CNIB')),
                ('justificatif_domicile', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Justificatif de résidence (eau, électricité, bail, certificat)')),
                ('attestation_non_engagement', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Attestation de non-engagement')),
                ('contrat_travail', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Contrat de travail')),
                ('attestation_travail', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Attestation de travail (<3 mois)')),
                ('quittance_salaire', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='quittance de salaire')),
                ('relevé_bancaire', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Relevé bancaire (12 mois) + RIB')),
                ('specimen_signature', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Spécimen de recueil de signature')),
                ('bulletin_1', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Bulletin de paie (mois -3)')),
                ('bulletin_2', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Bulletin de paie (mois -2)')),
                ('bulletin_3', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Bulletin de paie (mois -1)')),
                ('certificat_presence', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Certificat de présence au corps (âge départ retraite)')),
                ('geolocalisation', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Plan de géolocalisation')),
                ('garanties', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Garanties proposées (supports)')),
                ('recu_acompte', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name="Reçu des frais d'acompte de dossier")),
                ('fiche_demande', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Fiche de demande de financement')),
                ('statut_dossier', models.CharField(choices=[('vide', 'Dossier vide'), ('incomplet', 'Dossier incomplet'), ('complet', 'Dossier complet'), ('verification', 'En cours de vérification'), ('valide', 'Documents validés'), ('rejete', 'Documents rejetés')], default='vide', max_length=20)),
                ('commentaire_rejet', models.TextField(blank=True, help_text='Utilisez ce champ pour indiquer les documents manquants, les erreurs à corriger, ou toute autre remarque pertinente pour le client.', null=True, verbose_name="Commentaires du commercial ou de l'analyste")),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
