# Generated by Django 6.0.4 on 2026-08-19 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_app', '0001_initial'),
        ('commercial_app', '0001_initial'),
        ('leads_app', '0001_initial'),
        ('vehicul_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='demande_financement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads_app.demande_financement'),
        ),
        migrations.AddField(
            model_name='documents',
            name='offre_financement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='commercial_app.offre'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='effectue_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_effectuees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vehicul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance', to='vehicul_app.vehicul'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['statut', 'date_prochaine'], name='client_app__statut_c698d8_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['origine', 'statut'], name='client_app__origine_ca4caa_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['priorite', 'statut'], name='client_app__priorit_91c3b1_idx'),
        ),
    ]
