# Generated by Django 6.0.4 on 2026-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date_prochaine',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='kilometrage_actuel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='kilometrage_prochain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('planifiee', 'Planifiée'), ('confirmee', 'Confirmée'), ('en_cours', 'En cours'), ('effectuee', 'Effectuée'), ('depassee', 'Dépassée (non faite)'), ('annulee', 'Annulée')], default='planifiee', max_length=20),
        ),
    ]
