# Generated by Django 6.0.4 on 2026-08-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_alter_maintenance_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='marque',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
