# Generated by Django 6.0.4 on 2026-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_alter_maintenance_marque_alter_maintenance_modele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_prevue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
