# Generated by Django 6.0.4 on 2026-08-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0005_alter_maintenance_date_prevue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_prochaine',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
