# Generated by Django 6.0.4 on 2026-08-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0006_alter_maintenance_date_prochaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='geolocalisation',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='quittance_salaire',
        ),
        migrations.AddField(
            model_name='documents',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='documents',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude GPS'),
        ),
        migrations.AddField(
            model_name='documents',
            name='plan_geolocalisation',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Plan papier de géolocalisation (Optionnel)'),
        ),
    ]
