# Generated by Django 6.0.4 on 2026-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0007_remove_documents_geolocalisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='certificat_presence',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Certificat de présence au corps (FDS)'),
        ),
    ]
