# Generated by Django 6.0.4 on 2026-09-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_alter_documents_certificat_presence'),
        ('services_app', '0002_services_necessite_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='services_app.services'),
        ),
    ]
