# Generated by Django 6.0.4 on 2026-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0009_maintenance_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='type_maintenance',
            field=models.CharField(choices=[('vidange', 'Vidange'), ('revision', 'Révision complète'), ('pneumatiques', 'Pneumatiques'), ('freins', 'Freins/plaquettes'), ('climatisation', 'Climatisation'), ('batterie', 'Batterie'), ('autre', 'Autre')], max_length=30),
        ),
    ]
