# Generated by Django 6.0.4 on 2026-08-19 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commercial_app', '0001_initial'),
        ('vehicul_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='demande_financement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financement_type', models.CharField(blank=True, choices=[('maison', 'Maison'), ('externe', 'Externe')], max_length=50, null=True)),
                ('financement_par', models.CharField(blank=True, choices=[('fidelis', 'Fidelis'), ('alios', 'Alios')], max_length=50, null=True)),
                ('other_Vehicul_interested', models.CharField(blank=True, null=True)),
                ('apport', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('montant_finance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('mensualite', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('duree_mois', models.IntegerField(default=36)),
                ('revenus_mensuel', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('etape', models.CharField(choices=[('nouvelle', 'Nouvelle demande de financement'), ('en_attente', 'en attente de document'), ('en_cours', 'En cours de traitement'), ('demande_accordee_fidelis', 'Demande accordée chez Fidelis'), ('demande_accordee_alios', 'Demande accordée chez Alios'), ('demande_accordee_maison', 'Demande accordée (KOZ Finance)'), ('demande_refusee', 'Demande Refusé')], default='nouvelle', max_length=100)),
                ('notes_commercial', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('Vehicul_interested', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_financement', to='vehicul_app.vehicul', verbose_name="Véhicule d'intérêt")),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_financement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevisLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('other_Vehicul_interested', models.CharField(blank=True, null=True)),
                ('traited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Vehicul_interested_in_catalogue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Vehicul_interested', to='vehicul_app.vehicul')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_classifie', 'Non classifié'), ('gestion_de_statut', "Gérer l'état de la vente"), ('en_cours', 'En cours'), ('conclue', 'Conclue'), ('conclue_par_acceptation_offre_simple', "Conclue par acceptation d'offre simple"), ('conclue_par_acceptation_offre_financement', "Conclue par acceptation d'offre financement"), ('conclue_sur_acceptation_demande_financement', 'Conclue sur acceptation demande de financement'), ('perdue', 'Perdue'), ('perdue_par_refus_offre_simple', "Perdue par refus d'offre simple"), ('perdue_par_refus_offre_financement', "Perdue par refus d'offre financement"), ('perdue_par_rejet_dossier_offre_financement', 'Perdue par rejet de dossier (offre de financement)'), ('perdue_par_rejet_dossier_demande_financement', 'Perdue par rejet de dossier (demande de financement)')], default='non_classifie', max_length=70)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant total payé')),
                ('montant_finance', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Montant financé')),
                ('montant_total_paye', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant total payé')),
                ('mensualite', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Mensualité')),
                ('duree_mois', models.IntegerField(blank=True, null=True, verbose_name='Durée en mois')),
                ('echeances', models.JSONField(blank=True, default=list, help_text='Liste des échéances avec dates et montants', verbose_name='Échéances')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to=settings.AUTH_USER_MODEL)),
                ('demande_financement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vente', to='leads_app.demande_financement')),
                ('offre', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vente', to='commercial_app.offre')),
                ('vehicul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='vehicul_app.vehicul')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFinancement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('abandonne', 'Abandonné')], default='en_attente', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_financement', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_financement', to='leads_app.vente')),
            ],
            options={
                'verbose_name': 'Paiement de financement',
                'verbose_name_plural': 'Paiements de financement',
                'ordering': ['date_echeance'],
            },
        ),
    ]
