# Generated by Django 6.0.4 on 2026-08-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_financement',
            name='taux_interet',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='demande_financement',
            name='duree_mois',
            field=models.IntegerField(default=24),
        ),
    ]
