# Generated by Django 6.0.4 on 2026-09-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0002_demande_financement_taux_interet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_financement',
            name='etape',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle demande de financement'), ('convertis_en_offre', 'Convertis en offre de financement'), ('en_attente', 'en attente de document'), ('en_cours', 'En cours de traitement'), ('demande_accordee_fidelis', 'Demande accordée chez Fidelis'), ('demande_accordee_alios', 'Demande accordée chez Alios'), ('demande_accordee_maison', 'Demande accordée (KOZ Finance)'), ('demande_refusee', 'Demande Refusé')], default='nouvelle', max_length=100),
        ),
        migrations.AlterField(
            model_name='demande_financement',
            name='financement_par',
            field=models.CharField(blank=True, choices=[('fidelis', 'Fidelis'), ('koz', 'KOZ SERVICES')], max_length=50, null=True),
        ),
    ]
