# Generated by Django 6.0.4 on 2026-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_app', '0003_alter_demande_financement_etape_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_financement',
            name='etape',
            field=models.CharField(choices=[('nouvelle', 'Nouvelle demande de financement'), ('convertis_en_offre', 'Convertis en offre de financement'), ('en_attente', 'en attente de document'), ('en_cours', 'En cours de traitement'), ('demande_accordee_fidelis', 'Demande accordée chez Fidelis'), ('demande_accordee_alios', 'Demande accordée chez Alios'), ('demande_accordee_maison', 'Demande accordée (KOZ SERVICES)'), ('demande_refusee', 'Demande Refusé')], default='nouvelle', max_length=100),
        ),
    ]
