# Generated by Django 6.0.4 on 2026-08-19 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text='Classe FontAwesome (ex: fa-tools)', max_length=50, null=True, verbose_name='Icône')),
                ('couleur', models.CharField(default='#3b82f6', help_text='Couleur en hexadécimal (ex: #3b82f6)', max_length=7, verbose_name='Couleur')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Type de service',
                'verbose_name_plural': 'Types de services',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du service')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description du service')),
                ('description_courte', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description courte (pour les cartes)')),
                ('prix', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=12, null=True, verbose_name='Prix (FCFA)')),
                ('prix_promo', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Prix promo (FCFA)')),
                ('unite', models.CharField(blank=True, default='service', help_text='Ex: service, heure, mois, pièce', max_length=50, null=True, verbose_name='Unité')),
                ('duree_estimee', models.PositiveIntegerField(blank=True, default=30, help_text='Durée estimée en minutes', null=True, verbose_name='Durée estimée')),
                ('periodicite', models.CharField(blank=True, choices=[('unique', 'Unique'), ('mensuel', 'Mensuel'), ('trimestriel', 'Trimestriel'), ('semestriel', 'Semestriel'), ('annuel', 'Annuel')], default='unique', max_length=50, null=True, verbose_name='Périodicité')),
                ('est_disponible', models.BooleanField(blank=True, default=True, null=True, verbose_name='Service disponible')),
                ('est_vedette', models.BooleanField(blank=True, default=False, null=True, verbose_name='Service en vedette')),
                ('ordre', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name="Ordre d'affichage")),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='services/%Y/%m/%d/', verbose_name='Image principale')),
                ('compatible_vehicules', models.TextField(blank=True, help_text='Marques ou modèles compatibles (séparés par des virgules)', null=True, verbose_name='Véhicules compatibles')),
                ('est_forfait', models.BooleanField(blank=True, default=False, null=True, verbose_name='Est un forfait')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('services_inclus', models.ManyToManyField(blank=True, related_name='inclus_dans', to='services_app.services', verbose_name='Services inclus (pour les forfaits)')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services_app.typesservices', verbose_name='Type de service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services_images/%Y/%m/%d/', verbose_name='Image')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texte alternatif (SEO)')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_principale', models.BooleanField(default=False, verbose_name='Image principale')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services_app.services', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Image du service',
                'verbose_name_plural': 'Images des services',
                'ordering': ['ordre', 'date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], verbose_name='Note')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_services', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='services_app.services', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Avis sur service',
                'verbose_name_plural': 'Avis sur les services',
                'ordering': ['-date_creation'],
            },
        ),
    ]
