# Generated by Django 6.0.4 on 2026-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='necessite_maintenance',
            field=models.BooleanField(default=True, verbose_name='Ce service nécessite une planification de maintenance'),
        ),
        migrations.AddField(
            model_name='services',
            name='type_maintenance_associe',
            field=models.CharField(blank=True, choices=[('vidange', 'Vidange'), ('revision', 'Révision complète'), ('pneumatiques', 'Pneumatiques'), ('freins', 'Freins/plaquettes'), ('climatisation', 'Climatisation'), ('batterie', 'Batterie'), ('courroie', 'Courroie de distribution'), ('autre', 'Autre')], help_text='Rempli automatiquement le type de maintenance à la réservation de ce service', max_length=30, null=True, verbose_name='Type de maintenance correspondant'),
        ),
    ]
