# Generated by Django 6.0.4 on 2026-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0002_services_necessite_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='type_maintenance_associe',
            field=models.CharField(blank=True, choices=[('vidange', 'Vidange'), ('revision', 'Révision complète'), ('pneumatiques', 'Pneumatiques'), ('freins', 'Freins/plaquettes'), ('climatisation', 'Climatisation'), ('batterie', 'Batterie'), ('autre', 'Autre')], help_text='Rempli automatiquement le type de maintenance à la réservation de ce service', max_length=30, null=True, verbose_name='Type de maintenance correspondant'),
        ),
    ]
